### ISSUE TITLE
Error when repeat:true and required:false

### ISSUE THREAD

**Issue by nnoto** [mulesoft/osprey#135]
I have the definition:
```
/catalogs:
  get:
    queryParameters:
      aType:
        type: string
        required: false
        repeat: true
```
Up until just a few days ago, the API calls were working fine, with or without a supplied query parameter.
Now I receive the following error when /catalogs is called without a queryParameter, despite required being false:
```
{
  "errors":[
    {
      "type":"query",
      "dataPath":"aType",
      "keyword":"type",
      "schema":"string",
      "data":[
      ],
      "message":"Invalid type, expected string"
    }
  ],
  "stack":"BadRequestError: Request failed to validate against RAML definition\n    at createValidationError (/node_modules/osprey-method-handler/osprey-method-handler.js:665:14)\n    at ospreyQuery (/node_modules/osprey-method-handler/osprey-method-handler.js:207:19)\n    at handle (/node_modules/compose-middleware/lib/index.js:56:16)\n    at dispatch (/node_modules/compose-middleware/lib/index.js:39:20)\n    at next (/node_modules/compose-middleware/lib/index.js:37:24)\n    at ospreyAccepts (/node_modules/osprey-method-handler/osprey-method-handler.js:184:12)\n    at handle (/node_modules/compose-middleware/lib/index.js:56:16)\n    at dispatch /node_modules/compose-middleware/lib/index.js:39:20)\n    at next (/node_modules/compose-middleware/lib/index.js:37:24)\n    at discardBody (/node_modules/osprey-method-handler/osprey-method-handler.js:685:12)"
}
```

If I remove the 'repeat:true', the call succeeds.

**Comment by jstoiko** [comment]
can you post your whole RAML?

**Comment by nnoto** [comment]
Definitely, the error can be reproduced with:
#%RAML 0.8
title: tps
version: 0.1
mediaType: application/json

/catalogs:
  get:
    queryParameters:
      aType:
        type: string
        required: false
        repeat: true

Thanks!

**Comment by nnoto** [comment]
This began happening in the past few days. It seems raml-validate 1.1.0 is now being loaded instead of 1.0.6. It appears the only module that requires raml-validate 1.1.0 is raml-path-match. raml-path-match is version 2.1.0 now, whereas it was 2.0.0 when previously working.

**Comment by jstoiko** [comment]
I cannot reproduce. Here's how I tested:

`index.js`:
```javascript
var express = require('express')
var osprey = require('osprey')
var join = require('path').join

var PORT = 3000

var router = osprey.Router()

router.get('/catalogs', function (req, res) {
  res.json([
    {'id': 1},
    {'id': 2}
  ])
})

osprey.loadFile(join(__dirname, 'api.raml'))
  .then(function (middleware) {
    var app = express()

    app.use('/', middleware, router)

    app.listen(PORT, function () {
      console.log('Application listening on ' + PORT + '...')
    })
  })
```
I started the server:
```sh
$ node index.js 
Application listening on 3000...
```

and then I made the following request:
```sh
$ http localhost:3000/catalogs
HTTP/1.1 200 OK
(...)

[
    {
        "id": 1
    },
    {
        "id": 2
    }
]
```

The timing that you describe seems to correspond to the [latest release](https://github.com/mulesoft/osprey/releases/tag/v0.4.0). It would probably be a good idea to peg the versions you are using in your project's `package.json` just to be safe.

**Comment by nnoto** [comment]
I have Osprey explicitly set at version 0.3.2. 
Osprey has the sub dependency osprey-router, which, in this case is set to "^0.4.0".
Since 0.4.0 and 0.5.0 are the most current releases, 0.4.0 is being used for version 0.3.2 of osprey.
Osprey-router has the sub dependency raml-path-match, which, in this case is set to "^2.0.0".
Prior to 3 days ago, 2.1.0 didn't exist, so 2.0.0 was being used. However, with the new release of raml-path-match, 2.1.0 is now loaded for Osprey 0.3.2, causing the issue I'm seeing. Maybe raml-path-match should be pegged at "2.0.0" in the 0.3.2 release?

**Comment by jstoiko** [comment]
Now I understand what's happening. We use carets across the board so npm is installing whatever latest minor dependencies it finds.

It shouldn't have broken your code though so we should definitely look into this.

In the meantime, I suggest you either use the latest version of Osprey which I tested works with your RAML of explicitly set the versions of Osprey@0.3.2 and its dependencies (raml-path-match@2.0.0, etc) in your `package.json`.

**Comment by nnoto** [comment]
Got it, thanks for looking into it!
I'lll explicitly set the version of Osprey and its dependencies in package.json as you suggested for now

**Comment by brenda** [comment]
Hi!

I have the same issue with `required: false & repeat: true`

My files:

`trait searchable.raml`:

```
queryParameters:
  example:
    displayName: Example
    type: string
    required: false
    repeat: true
```

RAML:
```
#%RAML 0.8
version: 0.0.3

/assets:
  securedBy: [null]
  get:
    is: [ searchable ]
   ....
```

I'm receiving this message in all endpoints:
=> `error:  BadRequestError: Request failed to validate against RAML definition`

Detail:
```
2017-03-07T18:53:20.437Z - error:  BadRequestError: Request failed to validate against RAML definition
    at createValidationError (/Users/brendaguerra/Documents/Projects/asset-manager/node_modules/osprey-method-handler/osprey-method-handler.js:665:14)
    at ospreyQuery (/Users/brendaguerra/Documents/Projects/asset-manager/node_modules/osprey-method-handler/osprey-method-handler.js:207:19)
    at handle (/Users/brendaguerra/Documents/Projects/asset-manager/node_modules/compose-middleware/lib/index.js:56:16)
    at dispatch (/Users/brendaguerra/Documents/Projects/asset-manager/node_modules/compose-middleware/lib/index.js:39:20)
```

Packages versions:

```
    "osprey": {
      "version": "0.3.2",
      "from": "osprey@>=0.3.2 <0.4.0",
      "resolved": "https://registry.npmjs.org/osprey/-/osprey-0.3.2.tgz",
      "dependencies": {
        "finalhandler": {
          "version": "0.4.1",
          "from": "finalhandler@>=0.4.0 <0.5.0",
          "resolved": "https://registry.npmjs.org/finalhandler/-/finalhandler-0.4.1.tgz"
        },
        "form-data": {
          "version": "1.0.1",
          "from": "form-data@>=1.0.0-rc3 <2.0.0",
          "resolved": "https://registry.npmjs.org/form-data/-/form-data-1.0.1.tgz"
        },
        "object-assign": {
          "version": "4.1.1",
          "from": "object-assign@>=4.1.0 <5.0.0",
          "resolved": "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz"
        },
        "pluralize": {
          "version": "1.1.6",
          "from": "pluralize@>=1.1.1 <1.2.0",
          "resolved": "https://registry.npmjs.org/pluralize/-/pluralize-1.1.6.tgz"
        },
        "q": {
          "version": "0.9.7",
          "from": "q@0.9.7",
          "resolved": "https://registry.npmjs.org/q/-/q-0.9.7.tgz"
        },
        "raml-parser": {
          "version": "0.8.18",
          "from": "raml-parser@>=0.8.10 <0.9.0",
          "resolved": "https://registry.npmjs.org/raml-parser/-/raml-parser-0.8.18.tgz"
        }
      }
    },
    "osprey-method-handler": {
      "version": "0.10.3",
      "from": "osprey-method-handler@>=0.10.0 <0.11.0",
      "resolved": "https://registry.npmjs.org/osprey-method-handler/-/osprey-method-handler-0.10.3.tgz"
    },
    "osprey-resources": {
      "version": "0.7.0",
      "from": "osprey-resources@>=0.7.0 <0.8.0",
      "resolved": "https://registry.npmjs.org/osprey-resources/-/osprey-resources-0.7.0.tgz"
    },
    "osprey-router": {
      "version": "0.4.0",
      "from": "osprey-router@>=0.4.0 <0.5.0",
      "resolved": "https://registry.npmjs.org/osprey-router/-/osprey-router-0.4.0.tgz",
      "dependencies": {
        "array-flatten": {
          "version": "2.1.1",
          "from": "array-flatten@>=2.0.0 <3.0.0",
          "resolved": "https://registry.npmjs.org/array-flatten/-/array-flatten-2.1.1.tgz"
        }
      }

```

**Comment by jstoiko** [comment]
these two PATCH release should fix the issue:
https://github.com/mulesoft-labs/node-raml-validate/releases/tag/v1.1.1
https://github.com/mulesoft-labs/raml-path-match/releases/tag/v2.1.1
