### ISSUE TITLE
Not possible to install

### ISSUE THREAD

**Issue by zentoaku** [mulesoft/osprey#66]
Not possible to install via `npm install osprey -g` (Linux Mint 16 Petra)
```
../vendor/libxml/xpath.c: In function ‘xmlXPathNodeCollectAndTest’:
../vendor/libxml/xpath.c:12401:28: warning: comparison between ‘xmlElementType’ and ‘xmlXPathTypeVal’ [-Wenum-compare]
       } else if (cur->type == type) {
                            ^
../vendor/libxml/xpath.c:12402:13: warning: comparison between ‘xmlXPathTypeVal’ and ‘enum <anonymous>’ [-Wenum-compare]
    if (type == XML_NAMESPACE_DECL)
             ^
In file included from ../vendor/libxml/xpath.c:185:0:
../vendor/libxml/xpath.c: At top level:
../vendor/libxml/trionan.c:218:1: warning: ‘trio_is_negative’ defined but not used [-Wunused-function]
 trio_is_negative
 ^
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
../vendor/libxml/xpointer.c: In function ‘xmlXPtrNewRangeNodePoint’:
../vendor/libxml/xpointer.c:451:21: warning: comparison between ‘xmlElementType’ and ‘enum <anonymous>’ [-Wenum-compare]
     if (start->type != XPATH_POINT)
                     ^
  AR(target) Release/obj.target/vendor/libxml/xml.a
  COPY Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
make: g++: Command not found
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 127
make: Leaving directory `/home/xxx/dev/osprey/node_modules/osprey-resources/node_modules/osprey-method-handler/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/xxx/dev/osprey/node_modules/osprey-resources/node_modules/osprey-method-handler/node_modules/libxmljs
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/xxx/dev/osprey/npm-debug.log
npm ERR! not ok code 0
```

**Comment by blakeembrey** [comment]
Hi @zentoaku! Could you make sure `libxml` is installed using `sudo apt-get install libxml2-dev`? I've not tried installing on Linux, so please let me know :smile:

**Comment by blakeembrey** [comment]
I'm going to close this issue. `libxmljs` has been moved to an optional dependency and you'll need to find a way for it to build if you want to do XML validation. If you aren't using XML validation, it shouldn't matter.
