### ISSUE TITLE
Error when queryParameter is repeated but not required.

### ISSUE THREAD

**Issue by abhiofdoon** [mulesoft/osprey#84]
I have a query parameter which is not required but when it is present it can be repeated multiple time.

Here is how my RAML looks 

/instances:
  get:
    queryParameters:
      instance_state_name:
        type: string
        required: false
        repeat: true

This works fine for queries like this:
api/instances?instance_state_name=running&instance_state_name=stopped

but it produces an error in osprey for queries like this (when the optional parameter is not specified):
localhost:3000/api/instances

Error:
TypeError: Cannot read property 'valid' of undefined
    at /home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/osprey-method-handler/node_modules/raml-validate/raml-validate.js:320:27
    at Array.filter (native)
    at /home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/osprey-method-handler/node_modules/raml-validate/raml-validate.js:319:10
    at ospreyQuery (/home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:204:18)
    at next (/home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/compose-middleware/lib/index.js:34:21)
    at ospreyAccepts (/home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:184:12)
    at next (/home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/compose-middleware/lib/index.js:34:21)
    at discardBody (/home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:696:12)
    at next (/home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/compose-middleware/lib/index.js:34:21)
    at ospreyMethodHeader (/home/sharma52/dev/aws_mgr/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:260:12)

**Comment by blakeembrey** [comment]
Thanks for the report, I'll look into it ASAP.

**Comment by blakeembrey** [comment]
Thanks for the report @abhiofdoon - it's been corrected in a sub-dependency (https://github.com/mulesoft/node-raml-validate/commit/28e1494ccce330ba2adede39212edbbf6ad5c333). If you reinstall, it will pull down the latest patch version of the dependencies and this will be fixed.
